import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/open-sauce-one/400.css"; // regular
import "@fontsource/open-sauce-one/500.css"; // regular
import "@fontsource/open-sauce-one/700.css"; // bold (optional)
import "@fontsource/open-sauce-one/800.css"; // bold (optional)
import "@fontsource/open-sauce-one/900.css"; // bold (optional)

// or just import the base:
import "@fontsource/open-sauce-one";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sauce  antialiased`}>{children}</body>
    </html>
  );
}
